web_qlct/sono/urls.py
from django.urls import path
from .views import show_sono_page, chi_tiet_so_no, yc_them_so_no, them_sono


urlpatterns = [
    path('', show_sono_page, name='sono_page'),
    path('themsono/', yc_them_so_no, name='them_sono'),
    path('themsono/thuc_hien', them_sono, name='thuc_hien_them_sono'),
    path('chitiet-sono/<int:id_sono>', chi_tiet_so_no, name='chi_tiet_sono'),

]

web_qlct/web_qlct/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('qlct_ca_nhan/', include('qlct_ca_nhan.urls')),
    path('qlct_nhom/', include('qlct_nhom.urls')),
    path('sono/', include('sono.urls')),
    path('tienich/', include('tienich.urls')), 
]

web_qlct/sono/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


# Create your models here.
class SoNo(models.Model):
    # id = models.IntegerField(primary_key=True)
    ten_so_no = models.CharField(max_length=200, blank=True, null=True)
    so_tien = models.IntegerField(blank=True, null=True)
    doi_tac = models.CharField(max_length=200, blank=True, null=True)
    loai = models.IntegerField(blank=True, null=True)
    ngay_vay = models.DateTimeField(blank=True, null=True)
    ngay_tra = models.DateTimeField(blank=True, null=True)
    is_deleted = models.IntegerField(default=0)
    auth_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='sono')

    def __str__(self):
        return self.ten_so_no

    def is_due_date(self):
        if self.ngay_tra == timezone.now():
            return True
        else:
            return False

    class Meta:
        # managed = False
        db_table = 'so_no'

web_qlct/sono/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from .models import SoNo


# Create your views here.
def show_sono_page(request):
    current_user = request.user
    ds_sono = current_user.sono.all()
    context = {
        'ds_sono': ds_sono,
        'email': current_user.email,
    }
    return render(request, 'sono/sonopage.html', context=context)


def yc_them_so_no(request):
    current_user = request.user
    context = {
        'email': current_user.email,
    }
    return render(request, 'sono/themsono.html', context)


def them_sono(request):
    current_user = request.user
    context = {
        'email': current_user.email,
    }
    current_user = request.user
    ten = request.POST['ten_so_no']
    so_tien = request.POST['so_tien']
    doi_tac = request.POST['doi_tac']
    loai = request.POST['loai']
    ngay_vay = request.POST['ngay_vay_0'] + " " + request.POST['ngay_vay_1']
    ngay_tra = request.POST['ngay_tra_0'] + " " + request.POST['ngay_tra_1']
    if current_user.is_authenticated:
        current_user.sono.create(ten_so_no=ten, so_tien=so_tien, doi_tac=doi_tac,
                             loai=loai, ngay_vay=ngay_vay, ngay_tra=ngay_tra, is_deleted=0)
        return render(request, 'sono/themsono_thuchien.html', context)
    else:
        print('user invalid')
        return redirect('login')


def chi_tiet_so_no(request, id_sono):
    current_user = request.user
    sono_info = SoNo.objects.get(pk=id_sono)
    ds_sono = current_user.sono.all()
    context = {
        'sono': sono_info,
        'email': current_user.email,
        'ds_sono': ds_sono,
    }
    return render(request, 'sono/chitiet_sono.html', context=context)

web_qlct/sono/templates/sono/chitiet_sono.html
{% extends "sono/sono.html" %}
{% block content %}

<div class="w3-container w3-card w3-white w3-margin-bottom">
        <h4 class="w3-text-grey w3-padding-16"><i class="fa fa-suitcase fa-fw w3-margin-right w3-xxmedium w3-text-teal"></i>CHI TIẾT SỔ NỢ:</h4>
        <div class="w3-container">

                <div class="form-row field-ten_so_no">
                        <div>
                            <label for="id_ten_so_no">Tên sổ nợ:</label>
                                <h6>
                                    {{sono.ten_so_no}}
                                </h6>
                        </div>
                </div>

                <div class="form-row field-doi-tac">
                        <div>
                            <label for="id_doi_tac">Đối tác:</label>
                                <h6>
                                    {{sono.doi_tac}}
                                </h6>
                        </div>
                </div>

                <div class="form-row field-so_tien">
                        <div>
                                <label for="id_so_tien">Số tiền:</label>
                                <h6>
                                    {{sono.so_tien}}
                                </h6>
                        </div>
                </div>

                <div class="form-row field-ngay-vay">
                        <div>
                                <label for="id_ngay_vay">Ngày vay:</label>
                                <h6>
                                    {{sono.ngay_vay}}
                                </h6>
                        </div>
                </div>

                <div class="form-row field-ngay-tra">
                        <div>
                                <label for="id_ngay_tra">Ngày trả:</label>
                                <h6>
                                    {{sono.ngay_tra}}
                                </h6>
                        </div>
                </div>
        </div>
</div>

{% endblock %}

web_qlct/sono/templates/sono/sono.html
{% extends  "users/base1.html" %}
{% block rightcolumn %}

<div class="w3-bar w3-teal w3-card">
  <a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right" href="javascript:void(0)"
    onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
  <div class="w3-dropdown-hover w3-hide-small">
    <button class="w3-button w3-padding-large" title="Danh sách ví">Danh sách sổ nợ<i
        class="fa fa-caret-down"></i></span></button>
    <div class="w3-dropdown-content w3-card-4 w3-bar-block">
      {% for sono in ds_sono %}
      <!-- cần thêm link lấy chi tiết các sổ nợ -->
      <a href="{% url 'chi_tiet_sono' sono.id %}" class="w3-bar-item w3-button w3-center">{{ sono.ten_so_no }}</a>
      {% endfor %}
    </div>
  </div>

  <a href="{% url 'them_sono' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small w3-right" style="color:white">Thêm sổ nợ</a>
</div>

{% block content %}
{{context}}
{% endblock content %}

{% endblock %}

web_qlct/sono/templates/sono/sonopage.html
{% extends "sono/sono.html" %}
{% block content %}

<div class="w3-container w3-card w3-white w3-margin-bottom">
        <h4 class="w3-text-grey w3-padding-16"><i class="fa fa-suitcase fa-fw w3-margin-right w3-xxmedium w3-text-teal"></i>LỊCH SỬ VAY NỢ GẦN ĐÂY:</h4>
        {% for sono in ds_sono %}
        <div class="w3-container">

                <div class="form-row field-ten_so_no">
                        <div>
                            <label for="id_ten_so_no">Tên sổ nợ:</label>
                                <h6>
                                    {{sono.ten_so_no}}
                                </h6>
                        </div>
                </div>

                <div class="form-row field-doi-tac">
                        <div>
                            <label for="id_doi_tac">Đối tác:</label>
                                <h6>
                                    {{sono.doi_tac}}
                                </h6>
                        </div>
                </div>

                <div class="form-row field-so_tien">
                        <div>
                                <label for="id_so_tien">Số tiền:</label>
                                <h6>
                                    {{sono.so_tien}}
                                </h6>
                        </div>
                </div>

                <div class="form-row field-ngay-vay">
                        <div>
                                <label for="id_ngay_vay">Ngày vay:</label>
                                <h6>
                                    {{sono.ngay_vay}}
                                </h6>
                        </div>
                </div>

                <div class="form-row field-ngay-tra">
                        <div>
                                <label for="id_ngay_tra">Ngày trả:</label>
                                <h6>
                                    {{sono.ngay_tra}}
                                </h6>
                        </div>
                </div>
        </div>
        {% endfor %}
</div>

{% endblock %}

web_qlct/sono/templates/sono/themsono.html
{% extends  "sono/sono.html" %}
{% block content %}


<form action="{% url 'thuc_hien_them_sono' %}" method="post" id="sono_form" novalidate>
        {% csrf_token %}
        <div>
                <fieldset class="module aligned ">
                        <div class="form-row field-ten_so_no">
                                <div>
                                        <label for="id_ten_so_no">Tên sổ nợ:</label>
                                        <input type="text" name="ten_so_no" class="vTextField" maxlength="200"
                                                id="id_ten_so_no">
                                </div>
                        </div>
                        <div class="form-row field-so_tien">
                                <div>
                                        <label for="id_so_tien">Số tiền:</label>
                                        <input type="number" name="so_tien" class="vIntegerField" id="id_so_tien">
                                </div>
                        </div>
                        <div class="form-row field-doi_tac">
                                <div>
                                        <label for="id_doi_tac">Đối tác:</label>
                                        <input type="text" name="doi_tac" class="vTextField" maxlength="200"
                                                id="id_doi_tac">
                                </div>
                        </div>
                        <div class="form-row field-loai">
                                <div>
                                        <label for="id_loai">Loại:</label>
                                        <input type="number" name="loai" class="vIntegerField" id="id_loai">
                                </div>
                        </div>
                        <div class="form-row field-ngay_vay">
                                <div>
                                        <label for="id_ngay_vay_0">Ngày vay:</label>
                                        <p class="datetime">
                                                Date: <input type="text" name="ngay_vay_0" class="vDateField" size="10"
                                                        id="id_ngay_vay_0">
                                                <br>
                                                Time: <input type="text" name="ngay_vay_1" class="vTimeField" size="8"
                                                        id="id_ngay_vay_1">
                                        </p>
                                </div>
                        </div>
                        <div class="form-row field-ngay_tra">
                                <div>
                                        <label for="id_ngay_tra_0">Ngày trả:</label>
                                        <p class="datetime">
                                                Date: <input type="text" name="ngay_tra_0" class="vDateField" size="10"
                                                        id="id_ngay_tra_0">
                                                <br>
                                                Time: <input type="text" name="ngay_tra_1" class="vTimeField" size="8"
                                                        id="id_ngay_tra_1">
                                        </p>
                                </div>
                        </div>
                </fieldset>
                <div class="submit-row">
                        <input type="submit" value="Save" class="default" name="_save">
                </div>
        </div>
</form>
{% endblock %}

web_qlct/sono/templates/sono/themsono_thuchien.html
{% extends "sono/sono.html" %}
{% block content %}
<div class="w3-container w3-card w3-white w3-margin-bottom">
        <div class="w3-container w3-center w3-content" style="margin-top:155px; margin-bottom:150px; color:hsl(201, 18%, 37%);">
        <h1>Thêm sổ nợ thành công!</h1>
        </div>            
</div>
{% endblock %}