web_qlct/qlct_nhom/templates/qlct_nhom/urls.py
from django.urls import path
from .views import show_qlct_nhom_page, lay_bieu_do_cot, lay_bieu_do, yc_them_nhom, them_nhom, yc_them_nhom_user, yc_them_vi_nhom, them_vi_nhom, yc_them_chi_tieu, them_nhom_user, them_chitieu,lay_ls_chi_tieu, lay_ds_user


urlpatterns = [
    path('', show_qlct_nhom_page, name='qlct_nhom_page'),
    path('themnhom/', yc_them_nhom, name='themnhom'),
    path('themnhom/thuc_hien', them_nhom, name='thuc_hien_them_nhom'),
    path('ds-user/<int:id_nhom>', lay_ds_user, name='ds_user'),
    path('them-nhomuser/', yc_them_nhom_user, name='them_nhom_user'),
    path('them-nhomuser/thuc-hien', them_nhom_user, name='thuc_hien_them_nhom_user'),
    path('themvinhom/', yc_them_vi_nhom, name='them_vinhom'),
    path('themvinhom/thuc_hien', them_vi_nhom, name='thuc_hien_them_vinhom'),
    path('lsct/<int:id_vi>', lay_ls_chi_tieu, name = 'lay_ls_chi_tieu_nhom'),
    path('themchitieu', yc_them_chi_tieu, name='them_chitieu'),
    path('bieudo/<int:id_vi>', lay_bieu_do, name = 'lay_bieu_do_nhom'),
    path('bieudocot/<int:id_vi>', lay_bieu_do_cot, name = 'lay_bieu_do_cot_nhom'),
    path('themchitieu/thuc_hien', them_chitieu, name='thuc_hien_them_chi_tieu_nhom'),
]

web_qlct/qlct_nhom/urls.py
from django.urls import path
from .views import show_qlct_nhom_page, lay_bieu_do_cot, lay_bieu_do, yc_them_nhom, them_nhom, yc_them_nhom_user, yc_them_vi_nhom, them_vi_nhom, yc_them_chi_tieu, them_nhom_user, them_chitieu,lay_ls_chi_tieu, lay_ds_user


urlpatterns = [
    path('', show_qlct_nhom_page, name='qlct_nhom_page'),
    path('themnhom/', yc_them_nhom, name='themnhom'),
    path('themnhom/thuc_hien', them_nhom, name='thuc_hien_them_nhom'),
    path('ds-user/<int:id_nhom>', lay_ds_user, name='ds_user'),
    path('them-nhomuser/', yc_them_nhom_user, name='them_nhom_user'),
    path('them-nhomuser/thuc-hien', them_nhom_user, name='thuc_hien_them_nhom_user'),
    path('themvinhom/', yc_them_vi_nhom, name='them_vinhom'),
    path('themvinhom/thuc_hien', them_vi_nhom, name='thuc_hien_them_vinhom'),
    path('lsct/<int:id_vi>', lay_ls_chi_tieu, name = 'lay_ls_chi_tieu_nhom'),
    path('themchitieu', yc_them_chi_tieu, name='them_chitieu'),
    path('bieudo/<int:id_vi>', lay_bieu_do, name = 'lay_bieu_do_nhom'),
    path('bieudocot/<int:id_vi>', lay_bieu_do_cot, name = 'lay_bieu_do_cot_nhom'),
    path('themchitieu/thuc_hien', them_chitieu, name='thuc_hien_them_chi_tieu_nhom'),
]

web_qlct/sono/urls.py
from django.urls import path
from .views import show_sono_page, chi_tiet_so_no, yc_them_so_no, them_sono


urlpatterns = [
    path('', show_sono_page, name='sono_page'),
    path('themsono/', yc_them_so_no, name='them_sono'),
    path('themsono/thuc_hien', them_sono, name='thuc_hien_them_sono'),
    path('chitiet-sono/<int:id_sono>', chi_tiet_so_no, name='chi_tiet_sono'),

]

web_qlct/web_qlct/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('qlct_ca_nhan/', include('qlct_ca_nhan.urls')),
    path('qlct_nhom/', include('qlct_nhom.urls')),
    path('sono/', include('sono.urls')),
    path('tienich/', include('tienich.urls')), 
]

web_qlct/hoadon/models.py
from django.conf import settings
from django.db import models
from qlct_nhom.models import ViNhom
from qlct_ca_nhan.models import LinhVuc, ViCaNhan


# Create your models here.
class HoaDon(models.Model):
    # id = models.IntegerField(primary_key=True)
    ten_hoa_don = models.CharField(max_length=45, blank=True, null=True)
    so_tien = models.IntegerField(blank=True, null=True)
    ghi_chu = models.CharField(max_length=500, blank=True, null=True)
    thoi_gian_giao_dich = models.DateTimeField(blank=True, null=True)
    vi_nhom = models.ForeignKey(ViNhom, models.DO_NOTHING, blank=True, null=True)
    linh_vuc = models.ForeignKey(LinhVuc, models.DO_NOTHING)
    vi_ca_nhan = models.ForeignKey(ViCaNhan, models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.ten_hoa_don

    class Meta:
        # managed = False
        db_table = 'hoa_don'

web_qlct/qlct_nhom/models.py
from django.conf import settings
from django.db import models


# Create your models here.
class NhomUser(models.Model):
    auth_user = models.ForeignKey(settings.AUTH_USER_MODEL, models.DO_NOTHING)
    nhom = models.ForeignKey('Nhom', on_delete=models.DO_NOTHING)
    dinh_muc = models.IntegerField(null=True)
    is_leader = models.IntegerField(default=0)

    class Meta:
        # managed = False
        db_table = 'nhom_user'
        unique_together = (('auth_user', 'nhom'),)


class Nhom(models.Model):
    ten = models.CharField(max_length=50, default='Test')
    dinh_muc = models.IntegerField()
    is_deleted = models.IntegerField(default=0)
    users = models.ManyToManyField(settings.AUTH_USER_MODEL, through=NhomUser)

    def __str__(self):
        return self.ten

    class Meta:
        # managed = False
        db_table = 'nhom'


class ViNhom(models.Model):
    # id = models.IntegerField(primary_key=True)
    ten = models.CharField(max_length=45, blank=True, null=True)
    dinh_muc = models.IntegerField(blank=True, null=True)
    so_du = models.IntegerField(blank=True, null=True)
    auth_group = models.ForeignKey(Nhom, on_delete=models.CASCADE)

    def __str__(self):
        return self.ten

    class Meta:
        # managed = False
        db_table = 'vi_nhom'

web_qlct/sono/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


# Create your models here.
class SoNo(models.Model):
    # id = models.IntegerField(primary_key=True)
    ten_so_no = models.CharField(max_length=200, blank=True, null=True)
    so_tien = models.IntegerField(blank=True, null=True)
    doi_tac = models.CharField(max_length=200, blank=True, null=True)
    loai = models.IntegerField(blank=True, null=True)
    ngay_vay = models.DateTimeField(blank=True, null=True)
    ngay_tra = models.DateTimeField(blank=True, null=True)
    is_deleted = models.IntegerField(default=0)
    auth_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='sono')

    def __str__(self):
        return self.ten_so_no

    def is_due_date(self):
        if self.ngay_tra == timezone.now():
            return True
        else:
            return False

    class Meta:
        # managed = False
        db_table = 'so_no'

web_qlct/qlct_nhom/views.py
from django.contrib.auth.models import User
from django.http import Http404, HttpResponse
from django.shortcuts import redirect, render

from hoadon.views import lay_ds_hoa_don, them_hoa_don
from hoadon.models import HoaDon
from django.db.models import Sum

from .models import Nhom, NhomUser, ViNhom


def show_qlct_nhom_page(request):
    current_user = request.user
    ds_nhom = current_user.nhom_set.filter(is_deleted=0)
    ds_vi = []
    for nhom in ds_nhom:
        vis = nhom.vinhom_set.all()
        ds_vi += vis
    
    print(ds_vi)
    context = {
        'ds_nhom': ds_nhom,
        'email': current_user.email,
        'ds_vi': ds_vi,
    }
    return render(request, 'qlct_nhom/intro.html', context=context)


def yc_them_nhom(request):
    current_user = request.user
    ds_nhom = current_user.nhom_set.filter(is_deleted=0)
    ds_vi = []
    for nhom in ds_nhom:
        vis = nhom.vinhom_set.all()
        ds_vi += vis

    context = {
        'ds_nhom': ds_nhom,
        'email': current_user.email,
        'ds_vi': ds_vi,
    }
    return render(request, 'qlct_nhom/themnhom.html', context)


def them_nhom(request):
    current_user = request.user
    ds_nhom = current_user.nhom_set.filter(is_deleted=0)
    ds_vi = []
    for nhom in ds_nhom:
        vis = nhom.vinhom_set.all()
        ds_vi += vis

    context = {
        'ds_nhom': ds_nhom,
        'email': current_user.email,
        'ds_vi': ds_vi,
    }
    current_user = request.user
    ten = request.POST['ten']
    dinh_muc = request.POST['dinh_muc']

    nhom = Nhom(ten=ten, dinh_muc=dinh_muc)
    nhom.save()
    nhom_user = NhomUser(auth_user=current_user, nhom=nhom, is_leader=1)
    nhom_user.save()
  

    return render(request, 'qlct_nhom/themnhom_thuchien.html', context=context)


def lay_ds_user(request, id_nhom):
    current_user = request.user
    ds_nhom = current_user.nhom_set.filter(is_deleted=0)
    ds_vi = []
    for nhom in ds_nhom:
        vis = nhom.vinhom_set.all()
        ds_vi += vis
    id_user = NhomUser.objects.filter(nhom_id=id_nhom).values('auth_user_id')
    ds_dinhmuc = NhomUser.objects.filter(nhom_id=id_nhom).values('dinh_muc')
    ds_user = User.objects.filter(id__in=id_user)
    data = []
    print("số lượng: {} - {}".format(len(ds_dinhmuc), len(ds_user)))
    for i in range(0, len(id_user)):
        print(ds_user[i])
        print(ds_dinhmuc[i]['dinh_muc'])
        x = {'user': ds_user[i],
             'dinh_muc': ds_dinhmuc[i]['dinh_muc']}
        # x['user']: ds_user[i]
        # x['dinh_muc']: ds_dinhmuc[i]
        data.append(x)

    print(data)
    context = {
        'ds_user': data,
        'ds_nhom': ds_nhom,
        'email': current_user.email,
        'ds_vi': ds_vi,
    }
    return render(request, "qlct_nhom/ds_nhomuser.html", context=context)


def yc_them_nhom_user(request):
    current_user = request.user
    ds_nhom = current_user.nhom_set.filter(is_deleted=0)
    ds_vi = []
    for nhom in ds_nhom:
        vis = nhom.vinhom_set.all()
        ds_vi += vis
    current_user = request.user
    ds_nhom = current_user.nhom_set.filter(is_deleted=0)
    ds_user = User.objects.all()
    context = {
        'ds_nhom': ds_nhom,
        'ds_user':ds_user,
        'email': request.user.email,
        'ds_vi': ds_vi,
    }
    return render(request, 'qlct_nhom/them_nhomuser.html', context=context)


def them_nhom_user(request):
    id_nhom = request.POST['nhom']
    id_user = request.POST['user']
    dinh_muc = request.POST['dinh_muc']

    current_user = request.user
    ds_nhom = current_user.nhom_set.filter(is_deleted=0)
    ds_vi = []
    for nhom in ds_nhom:
        vis = nhom.vinhom_set.all()
        ds_vi += vis

    id_users = NhomUser.objects.filter(nhom_id=id_nhom).values('auth_user_id')
    if id_user in id_users:
        return Http404('user đã ở trong nhóm')
    nhom = Nhom.objects.get(pk=id_nhom)
    user = User.objects.get(pk=id_user)
    nhom_user = NhomUser(auth_user=user, nhom=nhom, dinh_muc=dinh_muc)
    nhom_user.save()
    context = {
        'ds_nhom': ds_nhom,
        'email': current_user.email,
        'ds_vi': ds_vi,
    }
    return render(request, 'qlct_nhom/them_nhomuser_thuchien.html', context=context)



def yc_them_vi_nhom(request):
    current_user = request.user
    ds_nhom = current_user.nhom_set.filter(is_deleted=0)
    ds_vi = []
    for nhom in ds_nhom:
        vis = nhom.vinhom_set.all()
        ds_vi += vis
    context = {
        'ds_nhom': ds_nhom,
        'email': current_user.email,
        'ds_vi': ds_vi,
    }

    return render(request, 'qlct_nhom/themvinhom.html', context=context)


def them_vi_nhom(request):

    current_user = request.user
    ds_nhom = current_user.nhom_set.filter(is_deleted=0)
    ds_vi = []
    for nhom in ds_nhom:
        vis = nhom.vinhom_set.all()
        ds_vi += vis
    context = {
        'ds_nhom': ds_nhom,
        'email': current_user.email,
        'ds_vi': ds_vi,
    }

    ten = request.POST['ten']
    dinh_muc = request.POST['dinh_muc']
    so_du = request.POST['so_du']
    id_nhom = request.POST["auth_group"]

    nhom = Nhom.objects.get(pk=id_nhom)
    nhom.vinhom_set.create(ten=ten, dinh_muc=dinh_muc, so_du=so_du)

    return render(request, 'qlct_nhom/themvinhom_thuchien.html', context)


def yc_them_chi_tieu(request):
    current_user = request.user
    ds_linhvuc = current_user.linhvuc_set.all()
    ds_vi = []
    ds_nhom = current_user.nhom_set.filter(is_deleted=0)
    for nhom in ds_nhom:
        ds_vi_nhom = nhom.vinhom_set.all()
        ds_vi.extend(ds_vi_nhom)
    context = {
        'ds_vi': ds_vi,
        'email': current_user.email,
        'ds_linhvuc': ds_linhvuc,
        'ds_nhom': ds_nhom,
    }
    return render(request, 'qlct_nhom/themchitieu.html', context)


def them_chitieu(request):
    current_user = request.user
    ten_hoa_don = request.POST["ten_hoa_don"]
    so_tien = request.POST["so_tien"]
    ghi_chu = request.POST["ghi_chu"]
    date = request.POST["thoi_gian_giao_dich_0"]
    time = request.POST["thoi_gian_giao_dich_1"]
    id_linhvuc = request.POST["linh_vuc"]
    id_vi = request.POST["vi_nhom"]

    current_user = request.user
    ds_nhom = current_user.nhom_set.filter(is_deleted=0)
    ds_vi = []
    for nhom in ds_nhom:
        vis = nhom.vinhom_set.all()
        ds_vi += vis

    context = {
        'ds_nhom': ds_nhom,
        'email': current_user.email,
        'ds_vi': ds_vi,
    }
    print(ghi_chu)

    if not current_user.is_authenticated:
        print('permission deni')
        return redirect('login')

    date_time = date + ' ' + time
    result = them_hoa_don(
        current_user=current_user,
        ten_hoa_don=ten_hoa_don,
        so_tien=so_tien,
        thoi_gian_giao_dich=date_time,
        id_linh_vuc=id_linhvuc,
        ghichu=ghi_chu,
        id_vi_nhom=id_vi,
    )

    return render(request, 'qlct_nhom/themchitieu_thuchien.html', context)


def lay_bieu_do(request, id_vi):
    # ds_hoa_don = lay_ds_hoa_don(id_vi_ca_nhan = id_vi)
    ds_linh_vuc = HoaDon.objects.filter(vi_nhom = id_vi).values('linh_vuc__ten').annotate(Sum('so_tien'))
    current_user = request.user
    ds_nhom = current_user.nhom_set.filter(is_deleted=0)
    ds_vi = []
    for nhom in ds_nhom:
        vis = nhom.vinhom_set.all()
        ds_vi += vis

    lv1 = ds_linh_vuc[0]['linh_vuc__ten']
    so1= ds_linh_vuc[0]['so_tien__sum']

    lv2 = ds_linh_vuc[1]['linh_vuc__ten']
    so2= ds_linh_vuc[1]['so_tien__sum']

    lv3 = ds_linh_vuc[2]['linh_vuc__ten']
    so3= ds_linh_vuc[2]['so_tien__sum']

    lv4 = ds_linh_vuc[3]['linh_vuc__ten']
    so4= ds_linh_vuc[3]['so_tien__sum']

    lv5 = ds_linh_vuc[4]['linh_vuc__ten']
    so5= ds_linh_vuc[4]['so_tien__sum']

    lv6 = ds_linh_vuc[5]['linh_vuc__ten']
    so6= ds_linh_vuc[5]['so_tien__sum']

    lv7 = ds_linh_vuc[6]['linh_vuc__ten']
    so7= ds_linh_vuc[6]['so_tien__sum']

    lv8 = ds_linh_vuc[7]['linh_vuc__ten']
    so8= ds_linh_vuc[7]['so_tien__sum']

    lv9 = ds_linh_vuc[8]['linh_vuc__ten']
    so9= ds_linh_vuc[8]['so_tien__sum']

    lv10 = ds_linh_vuc[9]['linh_vuc__ten']
    so10= ds_linh_vuc[9]['so_tien__sum']


    context = {
        'ds_nhom': ds_nhom,
        'email': current_user.email,
        'ds_vi': ds_vi,
        'lv1': lv1,
        'lv2': lv2,
        'lv3': lv3,
        'lv4': lv4,
        'lv5': lv5,
        'lv6': lv6,
        'lv7': lv7,
        'lv8': lv9,
        'lv9': lv9,
        'lv10': lv10,

        'so1': so1,
        'so2': so2,
        'so3': so3,
        'so4': so4,
        'so5': so5,
        'so6': so6,
        'so7': so7,
        'so8': so8,
        'so9': so9,
        'so10': so10,


        
    }

    print(ds_linh_vuc)
    return render(request, 'qlct_nhom/bieudotron.html', context)

from django.db.models.functions import Extract
def lay_bieu_do_cot(request, id_vi):

    ds_linh_vuc = HoaDon.objects.filter(vi_nhom = id_vi).values('linh_vuc__ten').annotate(Sum('so_tien'))
    current_user = request.user
    ds_nhom = current_user.nhom_set.filter(is_deleted=0)
    ds_vi = []
    for nhom in ds_nhom:
        vis = nhom.vinhom_set.all()
        ds_vi += vis


    ds_linh_vuc = HoaDon.objects.filter(vi_nhom = id_vi).values('linh_vuc__ten').annotate(Sum('so_tien'))

    so1= ds_linh_vuc[0]['so_tien__sum']

    so2= ds_linh_vuc[1]['so_tien__sum']

    so3= ds_linh_vuc[2]['so_tien__sum']

    so4= ds_linh_vuc[3]['so_tien__sum']

    so5= ds_linh_vuc[4]['so_tien__sum']

    so6= ds_linh_vuc[5]['so_tien__sum']

    so7= ds_linh_vuc[6]['so_tien__sum']

    so8= ds_linh_vuc[7]['so_tien__sum']

    so9= ds_linh_vuc[8]['so_tien__sum']

    so10= ds_linh_vuc[9]['so_tien__sum']



web_qlct/qlct_nhom/templates/qlct_nhom/bieudocot.html
{% extends "qlct_nhom/qlct_nhom.html" %}
{% block content %}

<html>
  <head>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
      var data = google.visualization.arrayToDataTable([
        ['Genre', 'Du Lịch', 'Điện', 'Sinh Hoạt', 'Thể Thao',
         'Giáo dục', 'Sức khỏe', 'Ăn uống', 'Vệ sinh', 'Giải trí', 'Học tập', { role: 'annotation' } ],
        ['Tháng 3', 10034, 24323, 20111, 32721, 18023, 5049, 8999, 12267, 140555, 109, ''],
        ['Tháng 4', 163450, 22033, 23122, 30266, 16423, 99878, 91123, 111234, 21312, 32032, ''],
        ['Tháng 5', {{so1}}, {{so2}}, {{so3}}, {{so4}}, {{so5}}, {{so6}}, {{so7}}, {{so8}}, {{so9}}, {{so10}}, '']
      ]);

      var options = {
        width: 885,
        height: 400,
        legend: { position: 'top', maxLines: 3 },
        bar: { groupWidth: '75%' },
        isStacked: true,
      };
      var chart = new google.visualization.ColumnChart(document.getElementById("columnchart_values"));
      chart.draw(data, options);
      }
    </script>
  </head>
  <body>
    <div id="columnchart_values" style="width: 885px; height: 400px;"></div>
  </body>
</html>

{% endblock %}

web_qlct/qlct_nhom/templates/qlct_nhom/themchitieu.html
{% extends  "qlct_nhom/qlct_nhom.html" %}
{% block content %}


<form action="{% url 'thuc_hien_them_chi_tieu_nhom' %}" method="post" id="hoadon_form" novalidate>
        {% csrf_token %}
        <div>
                <fieldset class="module aligned ">
                        <div class="form-row field-ten_hoa_don">
                                <div>
                                        <label for="id_ten_hoa_don">Tên hoá đơn:</label>
                                        <input type="text" name="ten_hoa_don" class="vTextField" maxlength="45"
                                                id="id_ten_hoa_don">
                                </div>
                        </div>
                        <div class="form-row field-so_tien">
                                <div>
                                        <label for="id_so_tien">Số tiền:</label>
                                        <input type="number" name="so_tien" class="vIntegerField" id="id_so_tien">
                                </div>
                        </div>
                        <div class="form-row field-ghi-chu">
                                <div>
                                        <label for="id_ghi_chu">Ghi chú:</label>
                                        <input type="text" name="ghi_chu" class="vTextField" maxlength="45"
                                                id="id_ghi_chu">
                                </div>
                        </div>
                        <div class="form-row field-thoi_gian_giao_dich">
                                <div>
                                        <label for="id_thoi_gian_giao_dich_0">Thời gian giao dịch:</label>
                                        <p class="datetime">
                                                Date: <input type="text" name="thoi_gian_giao_dich_0" class="vDateField"
                                                        size="10" id="id_thoi_gian_giao_dich_0">
                                                <br>
                                                Time: <input type="text" name="thoi_gian_giao_dich_1" class="vTimeField"
                                                        size="8" id="id_thoi_gian_giao_dich_1">
                                        </p>
                                </div>
                        </div>
                        <!-- <div class="form-row field-vi_nhom"> -->
                        <!-- <div> -->
                        <!-- <label for="id_vi_nhom">Ví nhóm:</label> -->
                        <!-- <div class="related-widget-wrapper"> -->
                        <!-- <select name="vi_nhom" id="id_vi_nhom"> -->
                        <!-- <option value="" selected>---------</option> -->
                        <!-- thêm vòng for cho ví nhóm vào đây -->
                        <!-- </select> -->
                        <!-- limk thêm ví nhóm -->
                        <!-- <a class="related-widget-wrapper-link add-related" id="add_id_vi_nhom" href=# title="Add another vi nhom"><img src="/static/admin/img/icon-addlink.svg" alt="Add"></a> -->
                        <!-- </div> -->
                        <!-- </div> -->
                        <!-- </div> -->
                        <div class="form-row field-linh_vuc">
                                <div>
                                        <label class="required" for="id_linh_vuc">Danh mục:</label>
                                        <div class="related-widget-wrapper">
                                                <!-- vòng for thêm lĩnh vực -->
                                                <select name="linh_vuc" required id="id_linh_vuc">
                                                        <option value=-1 selected>---------</option>
                                                        {% for linhvuc in ds_linhvuc %}
                                                                <option value= {{ linhvuc.id }}> {{ linhvuc }} </option>
                                                        {% endfor %}
                                                </select>
                                                <!-- link thêm lĩnh vực -->
                                                <a class="related-widget-wrapper-link add-related" id="add_id_linh_vuc"
                                                        href="{% url 'themlinhvuc' %}" title="Add another linh vuc"><img
                                                                src="/static/admin/img/icon-addlink.svg" alt="Add"></a>
                                        </div>
                                </div>
                        </div>
                        <div class="form-row field-vi-nhom">
                                <div>
                                        <label for="id_vi-nhom">Ví nhóm:</label>
                                        <div class="related-widget-wrapper">
                                                <!--vòng for thêm ví nhóm -->
                                                <select name="vi_nhom" id="id_vi-nhom">
                                                        <option value=-1 selected>---------</option>
                                                        {% for vi in ds_vi %}
                                                        <!-- cần thêm link vào đây (link dến lấy chi tiết ví) -->
                                                        <option value={{vi.id}}>{{ vi.ten }}</option>
                                                        {% endfor %}
                                                </select>
                                                <!-- link thêm ví -->
                                                <a class="related-widget-wrapper-link add-related"
                                                        id="add_id_vi-nhom" href="{% url 'them_vinhom' %}"
                                                        title="Add another vi ca nhan"><img
                                                                src="/static/admin/img/icon-addlink.svg" alt="Add"></a>
                                        </div>
                                </div>
                        </div>
        </div>
        </fieldset>
        <div class="submit-row">
                <input type="submit" value="Save" class="default" name="_save">
        </div>
</form>
{% endblock %}

web_qlct/qlct_nhom/templates/qlct_nhom/themnhom.html
{% extends  "qlct_nhom/qlct_nhom.html" %}
{% block content %}


<form action="{% url 'thuc_hien_them_nhom' %}" method="post" id="linhvuc_form" novalidate>
        {% csrf_token %}
        <div>
                <fieldset class="module aligned ">
                        <div class="form-row field-ten">
                                <div>
                                        <label for="id_ten">Tên nhóm</label>
                                        <input type="text" name="ten" class="vTextField" maxlength="45" id="id_ten">
                                </div>
                        </div>
                        <div class="form-row field-dinh_muc">
                                <div>
                                        <label for="id_dinh_muc">Định mức:</label>
                                        <input type="number" name="dinh_muc" class="vIntegerField" id="id_dinh_muc">
                                </div>
                        </div>
                </fieldset>
        </div>
        <div class="submit-row">
                <input type="submit" value="Save" class="default" name="_save">
        </div>
</form>
{% endblock %}

web_qlct/qlct_nhom/templates/qlct_nhom/themvinhom.html
{% extends  "qlct_nhom/qlct_nhom.html" %}
{% block content %}


<form action="{% url 'thuc_hien_them_vinhom' %}" method="post" id="vinhom_form" novalidate>
        {% csrf_token %}
        <div>
                <fieldset class="module aligned ">
                        <div class="form-row field-ten">
                                <div>
                                        <label for="id_ten">Tên:</label>
                                        <input type="text" name="ten" class="vTextField" maxlength="45" id="id_ten" value="hieu" >
                                </div>
                        </div>
                        <div class="form-row field-dinh_muc">
                                <div>
                                        <label for="id_dinh_muc">Định mức:</label>
                                        <input type="number" name="dinh_muc" class="vIntegerField" id="id_dinh_muc">
                                </div>
                        </div>
                        <div class="form-row field-so_du">
                                <div>
                                        <label for="id_so_du">Số dư:</label>
                                        <input type="number" name="so_du" class="vIntegerField" id="id_so_du">
                                </div>

                        </div>
                        <div class="form-row field-auth_group">
                                <div>
                                        <label class="required" for="id_auth_group">Auth group:</label>
                                        <div class="related-widget-wrapper">
                                                <select name="auth_group" required id="id_auth_group">
                                                        <option value="" selected>---------</option>
                                                        <!-- cần có biến ds_nhom ở context -->
                                                        {% for nhom in ds_nhom %} 
                                                                <option value= {{ nhom.id }}> {{ nhom }} </option>
                                                        {% endfor %}
                                                </select>
                                                <a class="related-widget-wrapper-link add-related"
                                                        id="add_id_auth_group" href="{% url 'themnhom' %}" title="Add another nhom"><img
                                                                src="/static/admin/img/icon-addlink.svg" alt="Add"></a>
                                        </div>
                                </div>
                        </div>
                </fieldset>
                <div class="submit-row">
                        <input type="submit" value="Save" class="default" name="_save">
                </div>
        </div>
</form>
</div>


{% endblock %}