web_qlct/qlct_ca_nhan/urls.py
from django.urls import path
from .views import them_vi, yc_them_vi, show_qlct_ca_nhan_page, yc_them_linhvuc, them_linhvuc, lay_ls_chi_tieu, yc_them_chi_tieu, them_chitieu, lay_bieu_do, lay_bieu_do_cot


urlpatterns = [
    path('', show_qlct_ca_nhan_page, name='qlct_canhan_page'),
    path('themvi', yc_them_vi, name='themvi'),
    path('themvi/thuc_hien', them_vi, name='thuc_hien_them_vi'),
    path('themlinhvuc', yc_them_linhvuc, name='themlinhvuc'),
    path('themlinhvuc/thuc_hien', them_linhvuc, name='thuc_hien_them_linhvuc'),
    path('lsct/<int:id_vi>', lay_ls_chi_tieu, name = 'lay_ls_chi_tieu' ),
    path('themchitieu/', yc_them_chi_tieu, name='themchitieu'),
    path('themchitieu/thuc_hien', them_chitieu, name='thuc_hien_them_chi_tieu'),
    path('bieudo/<int:id_vi>', lay_bieu_do, name = 'lay_bieu_do'),
    path('bieudocot/<int:id_vi>', lay_bieu_do_cot, name = 'lay_bieu_do_cot'),
]

web_qlct/sono/urls.py
from django.urls import path
from .views import show_sono_page, chi_tiet_so_no, yc_them_so_no, them_sono


urlpatterns = [
    path('', show_sono_page, name='sono_page'),
    path('themsono/', yc_them_so_no, name='them_sono'),
    path('themsono/thuc_hien', them_sono, name='thuc_hien_them_sono'),
    path('chitiet-sono/<int:id_sono>', chi_tiet_so_no, name='chi_tiet_sono'),

]

web_qlct/web_qlct/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('qlct_ca_nhan/', include('qlct_ca_nhan.urls')),
    path('qlct_nhom/', include('qlct_nhom.urls')),
    path('sono/', include('sono.urls')),
    path('tienich/', include('tienich.urls')), 
]

web_qlct/hoadon/models.py
from django.conf import settings
from django.db import models
from qlct_nhom.models import ViNhom
from qlct_ca_nhan.models import LinhVuc, ViCaNhan


# Create your models here.
class HoaDon(models.Model):
    # id = models.IntegerField(primary_key=True)
    ten_hoa_don = models.CharField(max_length=45, blank=True, null=True)
    so_tien = models.IntegerField(blank=True, null=True)
    ghi_chu = models.CharField(max_length=500, blank=True, null=True)
    thoi_gian_giao_dich = models.DateTimeField(blank=True, null=True)
    vi_nhom = models.ForeignKey(ViNhom, models.DO_NOTHING, blank=True, null=True)
    linh_vuc = models.ForeignKey(LinhVuc, models.DO_NOTHING)
    vi_ca_nhan = models.ForeignKey(ViCaNhan, models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.ten_hoa_don

    class Meta:
        # managed = False
        db_table = 'hoa_don'

web_qlct/qlct_ca_nhan/models.py
from django.conf import settings
from django.db import models


# Create your models here.
class ViCaNhan(models.Model):
    # id = models.IntegerField(primary_key=True)
    ten = models.CharField(max_length=45, blank=True, null=True)
    dinh_muc = models.IntegerField(blank=True, null=True)
    so_du = models.IntegerField(blank=True, null=True)
    auth_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    is_deleted = models.IntegerField(default=0)
    # 0 - chưa xóa, 1 - đã xóa

    def __str__(self):
        return self.ten

    class Meta:
        # managed = False
        db_table = 'vi_ca_nhan'


class LinhVuc(models.Model):
    # id = models.IntegerField(primary_key=True)
    ten = models.CharField(max_length=45, blank=True, null=True)
    loai = models.IntegerField(blank=True, null=True) # 1 là tiêu 0 là thu
    linh_vuc = models.ForeignKey('self', models.DO_NOTHING, blank=True, null=True)
    auth_user = models.ManyToManyField(settings.AUTH_USER_MODEL)

    def __str__(self):
        return self.ten

    class Meta:
        # managed = False
        db_table = 'linh_vuc'


# class AuthUserHasLinhVuc(models.Model):
#     auth_user = models.ForeignKey(settings.AUTH_USER_MODEL, models.DO_NOTHING, primary_key=True)
#     linh_vuc = models.ForeignKey('LinhVuc', models.DO_NOTHING)
#
#     class Meta:
#         # managed = False
#         db_table = 'auth_user_has_linh_vuc'
#         unique_together = (('auth_user', 'linh_vuc'),)

web_qlct/sono/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


# Create your models here.
class SoNo(models.Model):
    # id = models.IntegerField(primary_key=True)
    ten_so_no = models.CharField(max_length=200, blank=True, null=True)
    so_tien = models.IntegerField(blank=True, null=True)
    doi_tac = models.CharField(max_length=200, blank=True, null=True)
    loai = models.IntegerField(blank=True, null=True)
    ngay_vay = models.DateTimeField(blank=True, null=True)
    ngay_tra = models.DateTimeField(blank=True, null=True)
    is_deleted = models.IntegerField(default=0)
    auth_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='sono')

    def __str__(self):
        return self.ten_so_no

    def is_due_date(self):
        if self.ngay_tra == timezone.now():
            return True
        else:
            return False

    class Meta:
        # managed = False
        db_table = 'so_no'

web_qlct/qlct_ca_nhan/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from .models import LinhVuc, ViCaNhan
from hoadon.views import lay_ds_hoa_don, them_hoa_don
from hoadon.models import HoaDon
from django.db.models import Sum
import datetime

def show_qlct_ca_nhan_page(request):
    current_user = request.user
    ds_vi = current_user.vicanhan_set.filter(is_deleted=0)
    context = {
        'ds_vi': ds_vi,
        'email': current_user.email,
    }
    return render(request, 'qlct_ca_nhan/intro.html', context=context)


def yc_them_vi(request):
    current_user = request.user
    ds_vi = current_user.vicanhan_set.filter(is_deleted=0)
    context = {
        'ds_vi': ds_vi,
        'email': current_user.email,
    }
    return render(request, 'qlct_ca_nhan/themvi.html', context)


def them_vi(request):
    current_user = request.user
    ten = request.POST['ten']
    dinh_muc = request.POST['dinh_muc']
    sodu = request.POST['so_du']

    current_user = request.user
    ds_vi = current_user.vicanhan_set.filter(is_deleted=0)
    context = {
        'ds_vi': ds_vi,
        'email': current_user.email,
    }
    if current_user.is_authenticated:
        current_user.vicanhan_set.create(
            ten=ten, dinh_muc=dinh_muc, so_du=sodu, is_deleted=0)
        return render(request, 'qlct_ca_nhan/themvi_thuchien.html', context)
    else:
        print('user invalid')
        return redirect('login')


def yc_them_linhvuc(request):
    current_user = request.user
    ds_linhvuc = current_user.linhvuc_set.all()
    ds_vi = current_user.vicanhan_set.filter(is_deleted=0)
    context = {
        'email': current_user.email,
        'ds_linhvuc': ds_linhvuc,
        'ds_vi': ds_vi,
    }
    return render(request, 'qlct_ca_nhan/themlinhvuc.html', context=context)


def them_linhvuc(request):
    current_user = request.user
    print(request.POST)
    ten = request.POST['ten']
    loai = request.POST['loai']
    
    if str(loai) == "Chi tiêu":
        loai = 1
    else: 
        loai = 0
    id_linhvuc_cha = -1
    # print(id_linhvuc_cha)
    current_user = request.user
    ds_vi = current_user.vicanhan_set.filter(is_deleted=0)
    context = {
        'ds_vi': ds_vi,
        'email': current_user.email,
    }

    linh_vuc_cha = None

    if current_user.is_authenticated:
        linhvuc = current_user.linhvuc_set.create(ten=ten, loai=loai)
        if int(id_linhvuc_cha) != -1:
            linh_vuc_cha = LinhVuc.objects.get(pk=id_linhvuc_cha)
            linhvuc.linh_vuc = linh_vuc_cha
            linhvuc.save()

        return render(request, 'qlct_ca_nhan/themvi_thuchien.html', context)
    else:
        print('user invalid')
        return redirect('login')


def lay_ls_chi_tieu(request, id_vi):
    ds_hoa_don = lay_ds_hoa_don(id_vi_ca_nhan = id_vi)
    current_user = request.user
    ds_vi = current_user.vicanhan_set.filter(is_deleted=0)
    vi = ViCaNhan.objects.get(pk=id_vi)
    so_du = vi.so_du
    context = {
        'ds_chitieu': ds_hoa_don,
        'ds_vi': ds_vi,
        'email': current_user.email,
        'so_du': so_du,
    } 
    return render(request, 'qlct_ca_nhan/lsct.html', context)


def yc_them_chi_tieu(request):
    current_user = request.user
    ds_linhvuc = current_user.linhvuc_set.all()
    ds_vi = current_user.vicanhan_set.filter(is_deleted=0)
    context = {
        'ds_vi': ds_vi,
        'email': current_user.email,
        'ds_linhvuc': ds_linhvuc,
    }
    return render(request, 'qlct_ca_nhan/themchitieu.html', context)


def them_chitieu(request):
    current_user = request.user
    ten_hoa_don = request.POST["ten_hoa_don"]
    so_tien = request.POST["so_tien"]
    ghi_chu = request.POST["ghi_chu"]   
    id_linhvuc = request.POST["linh_vuc"]
    id_vi = request.POST["vi_ca_nhan"]

    current_user = request.user
    ds_vi = current_user.vicanhan_set.filter(is_deleted=0)
    context = {
        'ds_vi': ds_vi,
        'email': current_user.email,
    }
    print(ghi_chu)

    if not current_user.is_authenticated:
        print('permission deni')
        return redirect('login')

    date_time = datetime.datetime.now()
    result = them_hoa_don(
        current_user=current_user,
        ten_hoa_don=ten_hoa_don,
        so_tien=so_tien,
        thoi_gian_giao_dich=date_time,
        id_linh_vuc=id_linhvuc,
        ghichu=ghi_chu,
        id_vi_ca_nhan=id_vi,
    )

    return render(request, 'qlct_ca_nhan/themvi_thuchien.html', context)


def lay_bieu_do(request, id_vi):
    # ds_hoa_don = lay_ds_hoa_don(id_vi_ca_nhan = id_vi)
    ds_linh_vuc = HoaDon.objects.filter(vi_ca_nhan = id_vi).values('linh_vuc__ten').annotate(Sum('so_tien'))
    current_user = request.user
    ds_vi = current_user.vicanhan_set.filter(is_deleted=0)
    ds_ten = []
    ds_tien = []
    total = 0
    for i in ds_linh_vuc:
        ds_ten.append(i['linh_vuc__ten'])
        ds_tien.append(i['so_tien__sum'])
        total += int(i['so_tien__sum'])
    context = {
        'ds_vi': ds_vi,
        'email': current_user.email,
        'ds_ten': ds_ten,
        'ds_tien': ds_tien,
        'total': total
    }

    return render(request, 'qlct_ca_nhan/bieudotron.html', context)

from django.db.models.functions import Extract
def lay_bieu_do_cot(request, id_vi):

    current_user = request.user
    ds_vi = current_user.vicanhan_set.filter(is_deleted=0)

    ds_linh_vuc = HoaDon.objects.filter(vi_ca_nhan = id_vi).values('linh_vuc__ten').annotate(Sum('so_tien'))

    so1= ds_linh_vuc[0]['so_tien__sum']

    so2= ds_linh_vuc[1]['so_tien__sum']

    so3= ds_linh_vuc[2]['so_tien__sum']

    so4= ds_linh_vuc[3]['so_tien__sum']

    so5= ds_linh_vuc[4]['so_tien__sum']

    so6= ds_linh_vuc[5]['so_tien__sum']

    so7= ds_linh_vuc[6]['so_tien__sum']

    so8= ds_linh_vuc[7]['so_tien__sum']

    so9= ds_linh_vuc[8]['so_tien__sum']

    so10= ds_linh_vuc[9]['so_tien__sum']


    context = {
        'ds_vi': ds_vi,
        'email': current_user.email,
        'so1': so1,
        'so2': so2,
        'so3': so3,
        'so4': so4,
        'so5': so5,
        'so6': so6,
        'so7': so7,
        'so8': so8,
        'so9': so9,
        'so10': so10,
    }

    print(ds_linh_vuc)
    return render(request, 'qlct_ca_nhan/bieudocot.html', context)

web_qlct/qlct_ca_nhan/templates/qlct_ca_nhan/bieudocot.html
{% extends "qlct_ca_nhan/qlct_canhan.html" %}
{% block content %}

<html>
  <head>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  </head>
  <body>
    <canvas id="myChart" height="450" width="600" style="margin-top: 30px;"></canvas>
    <div style="margin-top: 50px; margin-left: auto; 
    margin-right: auto;">
    
      <table class="table-hover table " style="color: black; width: 400px;">
        <tbody >
            <tr>
                <td>Total</td>
                <td>-10.000</td>
            </tr>            
        </tbody>
    </table>
  </div>
    <script>
      let ctx = document.getElementById('myChart').getContext('2d');
  
  var data = {
      labels: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
      datasets: [
          {
              label: "Chi tiêu",
              backgroundColor: "red",
              data: [4,3,5,6,7,9,87,0,87,100]
          }
      ]
  };
  
  var myBarChart = new Chart(ctx, {
      type: 'bar',
      data: data,
      options: {
          barValueSpacing: 20,
          scales: {
              yAxes: [{
                  ticks: {
                      min: 0,
                  }
              }]
          }
      }
  });
    </script>
  </body>
</html>

{% endblock %}

web_qlct/qlct_ca_nhan/templates/qlct_ca_nhan/bieudotron.html
{% extends "qlct_ca_nhan/qlct_canhan.html" %}
{% block content %}
<html>
  <head>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.min.js"></script>

  </head>
  <body>
    <div style="width: 600px;">
    <canvas id="myChart" height="450" width="600" style="margin-top: 30px;"></canvas>
    <div style="margin-top: 50px; margin-left: auto; 
    margin-right: auto;">
    
      <table class="table-hover table " style="color: black; width: 600px;">
        <tbody >
            <tr>
                <td>Total</td>
                <td>{{total}}</td>
            </tr>            
        </tbody>
    </table>
  </div>
  </div>
    <script>
      let ctx = document.getElementById('myChart').getContext('2d');
      let labels = {{ ds_ten | safe}}; 
      let datas = {{ds_tien | safe}};
  console.log(labels);
  var data = {
      labels: labels,
      datasets: [
          {
              label: "Số tiền",
              backgroundColor: "red",
              data: datas
          }
      ]
  };
  
  var myBarChart = new Chart(ctx, {
      type: 'bar',
      data: data,
      options: {
          barValueSpacing: 20,
          scales: {
              yAxes: [{
                  ticks: {
                      min: 0,
                  }
              }]
          }
      }
  });
    </script>
  </body>

</html>

{% endblock %}

web_qlct/qlct_ca_nhan/templates/qlct_ca_nhan/lsct.html
{% extends "qlct_ca_nhan/qlct_canhan.html" %}
{% block content %}
    
      <div class="w3-container w3-card w3-white w3-margin-bottom">
        <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-suitcase fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i>LỊCH SỬ CHI TIÊU</h2>
        <h2 class="w3-text-grey w3-padding-1">  SỐ DƯ HIỆN TẠI: {{ so_du }} </h2>
        {% for chitieu in ds_chitieu %}
          <div class="w3-container">
          <h5 class="w3-opacity"><b>{{chitieu.ten_hoa_don}}</b></h5>
          <h6 class="w3-text-teal"><i class="fa fa-calendar fa-fw w3-margin-right"></i>{{chitieu.thoi_gian_giao_dich}}</h6>
          <h4 class="w3-text-red">{{chitieu.so_tien}}</h4>
          <p>{{ chitieu.ghi_chu }}</p>
          <hr>
        </div>
        {% endfor %}
      </div>

{% endblock content %}

web_qlct/qlct_ca_nhan/templates/qlct_ca_nhan/qlct_canhan.html
{% extends  "users/base1.html" %} 
{% block rightcolumn %}

<div class="w3-bar w3-teal w3-card" >
    <a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right" href="javascript:void(0)" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
    <div class="w3-dropdown-hover w3-hide-small">
    <button class="w3-button w3-padding-large" title="Danh sách ví">Danh sách ví<i class="fa fa-caret-down"></i></span></button>     
    <div class="w3-dropdown-content w3-card-4 w3-bar-block">
      {% for vi in ds_vi %}
      <!-- cần thêm link vào đây (link dến lấy chi tiết ví) -->
        <a href="{% url 'lay_ls_chi_tieu' vi.id %}" class="w3-bar-item w3-button w3-center">{{ vi.ten }}</a> 
      {% endfor %}
      <a href="{% url 'themvi' %}" class="w3-bar-item w3-button w3-center">Thêm ví</a>
    </div>
  </div> 
  <!-- thêm link lấy ds lịch sử chi tiêu -->
    <!-- <a href="#" class="w3-bar-item w3-button w3-padding-large w3-hide-small" style="color:white">Lịch Sử Chi Tiêu</a> -->
    <div class="w3-dropdown-hover w3-hide-small">
      <button class="w3-padding-large w3-button" title="More">Thống kê <i class="fa fa-caret-down"></i></button>     
      <div class="w3-dropdown-content w3-bar-block w3-card-4">
        <!-- các link lấy biểu đồ -->
        {% for vi in ds_vi %}
        <a href="{% url 'lay_bieu_do' vi.id %}" class="w3-bar-item w3-button">{{vi.ten}}</a>
        {% endfor %}
      </div>
    </div>



    <!-- link thêm lĩnh vực -->
    <a href="{% url 'themlinhvuc' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small" style="color:white">Thêm danh mục</a>
<!-- link thêm hóa đơn chi tiêu -->
    <a href="{% url 'themchitieu' %}" class="w3-bar-item w3-button w3-padding-large w3-hide-small w3-right" style="color:white">Thêm chi tiêu</a>
    </div>

    {% block content %}
    {{context}}
    {% endblock content %}

 {% endblock %} 

web_qlct/qlct_ca_nhan/templates/qlct_ca_nhan/themchitieu.html
{% extends  "qlct_ca_nhan/qlct_canhan.html" %}
{% block content %}


<form action="{% url 'thuc_hien_them_chi_tieu' %}" method="post" id="hoadon_form" novalidate>
        {% csrf_token %}
        <div>
                <fieldset class="module aligned ">
                        <div class="form-row field-ten_hoa_don">
                                <div>
                                        <label for="id_ten_hoa_don">Tên hoá đơn:</label>
                                        <input type="text" name="ten_hoa_don" class="vTextField" maxlength="45"
                                                id="id_ten_hoa_don">
                                </div>
                        </div>
                        <div class="form-row field-so_tien">
                                <div>
                                        <label for="id_so_tien">Số tiền:</label>
                                        <input type="number" name="so_tien" class="vTextField" id="id_so_tien">
                                </div>
                        </div>
                        <div class="form-row field-ghi-chu">
                                <div>
                                        <label for="id_ghi_chu">Ghi chú:</label>
                                        <input type="text" name="ghi_chu" class="vTextField" maxlength="45"
                                                id="id_ghi_chu">
                                </div>
                        </div>
                
                        <!-- <div class="form-row field-vi_nhom"> -->
                        <!-- <div> -->
                        <!-- <label for="id_vi_nhom">Ví nhóm:</label> -->
                        <!-- <div class="related-widget-wrapper"> -->
                        <!-- <select name="vi_nhom" id="id_vi_nhom"> -->
                        <!-- <option value="" selected>---------</option> -->
                        <!-- thêm vòng for cho ví nhóm vào đây -->
                        <!-- </select> -->
                        <!-- limk thêm ví nhóm -->
                        <!-- <a class="related-widget-wrapper-link add-related" id="add_id_vi_nhom" href=# title="Add another vi nhom"><img src="/static/admin/img/icon-addlink.svg" alt="Add"></a> -->
                        <!-- </div> -->
                        <!-- </div> -->
                        <!-- </div> -->
                        <div class="form-row field-linh_vuc">
                                <div>
                                        <label class="required" for="id_linh_vuc">Danh mục:</label>
                                        <div class="related-widget-wrapper">
                                                <!-- vòng for thêm lĩnh vực -->
                                                <select name="linh_vuc" required id="id_linh_vuc">
                                                        <option value=-1 selected>---------</option>
                                                        {% for linhvuc in ds_linhvuc %}
                                                                <option value= {{ linhvuc.id }}> {{ linhvuc }} </option>
                                                        {% endfor %}
                                                </select>
                                                <!-- link thêm lĩnh vực -->
                                                <a class="related-widget-wrapper-link add-related" id="add_id_linh_vuc"
                                                        href="{% url 'themlinhvuc' %}" title="Add another linh vuc"><img
                                                                src="/static/admin/img/icon-addlink.svg" alt="Add"></a>
                                        </div>
                                </div>
                        </div>
                        <div class="form-row field-vi_ca_nhan">
                                <div>
                                        <label for="id_vi_ca_nhan">Ví cá nhân:</label>
                                        <div class="related-widget-wrapper">
                                                <!--vòng for thêm ví cá nhân -->
                                                <select name="vi_ca_nhan" id="id_vi_ca_nhan">
                                                        <option value=-1 selected>---------</option>
                                                        {% for vi in ds_vi %}
                                                        <!-- cần thêm link vào đây (link dến lấy chi tiết ví) -->
                                                        <option value={{vi.id}}>{{ vi.ten }}</option>
                                                        {% endfor %}
                                                </select>
                                                <!-- link thêm ví -->
                                                <a class="related-widget-wrapper-link add-related"
                                                        id="add_id_vi_ca_nhan" href="{% url 'themvi' %}"
                                                        title="Add another vi ca nhan"><img
                                                                src="/static/admin/img/icon-addlink.svg" alt="Add"></a>
                                        </div>
                                </div>
                        </div>
        </div>
        </fieldset>
        <div class="submit-row">
                <input type="submit" value="Save" class="default" name="_save">
        </div>
</form>
{% endblock %}

web_qlct/qlct_ca_nhan/templates/qlct_ca_nhan/themlinhvuc.html
{% extends  "qlct_ca_nhan/qlct_canhan.html" %}
{% block content %}


<form action="{% url 'thuc_hien_them_linhvuc' %}" method="post" id="linhvuc_form" novalidate>
        {% csrf_token %}
        <div>
                <fieldset class="module aligned ">
                        <div class="form-row field-ten">
                                <div>
                                        <label for="id_ten">Tên:</label>
                                        <input type="text" name="ten" class="vTextField" maxlength="45" id="id_ten">
                                </div>
                        </div>
                        <div class="form-row field-loai">
                                <div>
                                        <label for="id_loai">Loại:</label>
                                        <select  name="loai" class="vTextField" id="id_loai">
                                                <option value="Chi tiêu">Chi tiêu</option>
                                                <option value="Thu nhập">Thu nhập</option>
                                        </select>
                                </div>
                        </div>
                        <div class="form-row field-linh_vuc">
                                <div>
                                        <label for="id_linh_vuc">Danh sách danh mục:</label>
                                  
                                        <!-- <div class="related-widget-wrapper">
                                                <select name="linh_vuc" id="id_linh_vuc">
                                                        <option value=-1 selected>---------</option>
                                                        {% for linhvuc in ds_linhvuc %}
                                                                <option value= {{ linhvuc.id }}> {{ linhvuc }} </option>
                                                        {% endfor %}
                                                </select> -->
                                              
                                                <!-- <a class="related-widget-wrapper-link add-related" id="add_id_linh_vuc"
                                                        href="{% url 'themlinhvuc' %}" title="Add another linh vuc">
                                                        <img src="/static/admin/img/icon-addlink.svg" alt="Add"></a> -->
                                        <!-- </div> -->
                                </div>
                        </div>
                        {% for linhvuc in ds_linhvuc %}
                        <div class="form-row field-linh_vuc" style="font-size: 14px;">
                                <div>
                                        {{ linhvuc }}
                                </div>
                        </div>
                        {% endfor %}
                </fieldset>
                <div class="submit-row">
                        <input type="submit" value="Save" class="default" name="_save">
                </div>
        </div>
</form>
</div>
<!-- END Content -->
{% endblock %}

web_qlct/qlct_ca_nhan/templates/qlct_ca_nhan/themvi.html
{% extends  "qlct_ca_nhan/qlct_canhan.html" %}
{% block content %}


<form action="{% url 'thuc_hien_them_vi' %}" method="post" id="linhvuc_form" novalidate>
        {% csrf_token %}
        <div>
                <fieldset class="module aligned ">
                        <div class="form-row field-ten">
                                <div>
                                        <label for="id_ten">Tên ví:</label>
                                        <input type="text" name="ten" class="vTextField" maxlength="45" id="id_ten">
                                </div>
                        </div>
                        <div class="form-row field-dinh_muc">
                                <div>
                                        <label for="id_dinh_muc">Định mức:</label>
                                        <input type="number" name="dinh_muc" class="vIntegerField" id="id_dinh_muc">
                                </div>
                        </div>
                        <div class="form-row field-so_du">
                                <div>
                                        <label for="id_so_du">Số dư:</label>
                                        <input type="number" name="so_du" class="vIntegerField" id="id_so_du">
                                </div>
                        </div>
                </fieldset>
        </div>
        <div class="submit-row">
                <input type="submit" value="Save" class="default" name="_save">
        </div>
</form>
{% endblock %}

web_qlct/qlct_ca_nhan/templates/qlct_ca_nhan/themvi_thuchien.html
{% extends "qlct_ca_nhan/qlct_canhan.html" %}
{% block content %}
<div class="w3-container w3-card w3-white w3-margin-bottom">
        <div class="w3-container w3-center w3-content" style="margin-top:155px; margin-bottom:150px; color:hsl(201, 18%, 37%);">
        <h1>Thành công!</h1>
        </div>            
</div>
{% endblock %}